- src/wasm-pack/package-code.md
- src/wasm-pack/run-the-code.md
In [8.2.4](https://rustwasm.github.io/book/wasm-pack/package-code.html), it currently says
> ...
In your project directory run the following command:
`$ wasm-pack init --scope MYSCOPE`
where `MYSCOPE` is your name **or something**.
...
To me, `or something` implies that `MYSCOPE` can be anything.
This is what I thought when I was following the tutorial, so I chose `hello-world` as my scope, and got an error message.
It turns out, according to the [npm scope documentation](https://docs.npmjs.com/misc/scope):
> Each npm user/organization has their own scope, and **only you can add packages in your scope**.
To solve this, I simply replaced the misleading `your name or something` with `your npm username`.
> Require `MYSCOPE` to be your npm username.

- src/introduction.md
- src/js-ffi.md
- src/tools.md
There were a few links left in the book that pointed to the old rust-lang-nursery repos.
> Update links pointing to the old rust-nursery to the new rustwasm organisation

- src/hello-world.md
While underscores make sense for Rust functions I think this change makes it a bit more approachable for someone coming from JavaScript
> switch to camel case for JS code

- README.md
There aren't any legacy issues in the other repo now that they've all been migrated :)
> Remove legacy issues link in README

- .github/ISSUE_TEMPLATE/----misleading-unclear-docs.md
- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/---feature-request.md
- .github/ISSUE_TEMPLATE/---other.md
When coming to a project sometimes people need to file issues! With different types of issues though different kinds of information is warranted to solve it. Sometimes it's not even an issue but a feature request! This commit adds some issue templates to make it easy for people to file what information we the maintainers need to make better docs.
cc/ @rustwasm/book 
I'd like to hear more of your opinions before we merge this. Should we add more types of issue templates? Do these need to be improved?
> Add issue templates

- src/game-of-life/implementing.md
Re: #29 
Looking around, it seemed that this was the only place that talked about crossing the boundaries and performance. It didn't look like it needed any smoothing out given the language.
> Removed legacy mentions of slow crossing-boundary calling

- src/js-ffi.md
I didn't remove the *likely to change* warning since it seems the attribute might go through a name change before stabilising, but that can be easily amended in the future.
> Document the current state of import and export naming

- src/SUMMARY.md
- src/game-of-life/implementing.md
- src/game-of-life/publishing.md
- src/game-of-life/time-profiling.md
- src/wasm-pack/rust-code.md
> Add explaination of the raw wasm module

- src/game-of-life/setup.md
- src/js-ffi.md
- src/wasm-pack/rust-code.md
Some `#![feature]`s are no longer required on the latest nightlies
rust-lang/rust#52445
rust-lang/rust#52353
> Use stabilized wasm attributes

- src/tools.md
I completed the rustwasm book yesterday (I really enjoyed it, thanks!) and I noticed that the previously linked issue for the wasm size profiler project suggestion was closed with a reference to twiggy so I figured it should be updated here.
> Replace size profiler project suggestion w/ twiggy

- .travis.yml
- src/game-of-life/debugging.md
- src/game-of-life/hello-world.md
- src/game-of-life/implementing.md
- src/game-of-life/rules.md
- src/game-of-life/time-profiling.md
Link handling is changed slightly in 0.2.0, they are now relative to the file instead of the book's root
https://github.com/rust-lang-nursery/mdBook/releases/tag/v0.2.0
In a case of great timing, this release came just a couple hours after it was requested in #64 :+1:
> Update to mdbook 0.2.0

- src/background-and-concepts.md
I think this touches on issue #28 a bit. Potentially opening an issue for this page specifically might make sense. I'm happy to do that if you all think that's the right direction.
**Summary**
I replaced "it" with wasm and added some of the acronyms in parentheses after the full word.
The motivation behind this change was to make it more clear for someone who isn't familiar with wasm when they're reading the docs.
> specifying acronyms in Background And Concepts

- src/game-of-life/hello-world.md
**Summary**
It prevents the game of life template from npm run errors. If it's run as currently described (npm link and afterwards npm install) then the wasm-game-of-life won't be locally launched properly! 🤔 This PR changes the sequence of the described steps:
1. npm install
2. npm link
> Sequence Error: Fixes the correct npm link/install sequence.

- src/reference/crates.md
**Summary**
Add `wasm-bindgen-futures` to crates you should know section 🤔. Intention? To extend the documentation (and to get used to the process of the team and add even more features in the future!)
Fixes Issue #82 
> Add wasm-bindgen-features on the crates you should know 

- src/reference/crates.md
**Summary**
The header for this recommended crate typoed 'futures' as 'features', momentarily confusing and leading me to check if there was another crate bundling multiple `wasm-bindgen` feature crates like `wasm-bindgen-futures`.
> Fix typo in wasm-bindgen-futures crate name

- src/game-of-life/hello-world.md
**Summary**
Changes 'wasm-pack init' to 'wasm-pack build' fixes #102
> Change 'wasm-pack init' to 'wasm-pack build'

- src/game-of-life/hello-world.md
Hey, after reading the book I think it would be clearer to mention Rust 1.30 or newer over the nightly compiler. I think it was somewhat confusing after going through the setup [here](https://rustwasm.github.io/book/game-of-life/setup.html#the-rust-toolchain) and then later see the mention of the nightly compiler. This is pity and maybe doesn't makes sense but I thought I would make this PR and write this, please let me know what you guys think. Thanks!
> Replace nightly compiler with Rust 1.30 or newer

- src/reference/js-ffi.md
Adds a section to the JS FFI chapter describing how to emit (Rust) and consume (JavaScript) wasm custom sections
> Document custom sections

- src/game-of-life/interactivity.md
- src/game-of-life/time-profiling.md
In implementing.md, drawGrid/drawCells is reversed compared to all other cases throughout the tutorial. This results in slightly different rendering when interacting—the lines will be slimmer when drawing the cells after the grid—if you forget to change this order in the render loop later on.
> Make drawGrid/drawCells order the same everywhere

- src/reference/js-ffi.md
**Summary**
The original link says: "This method is not the most efficient way of fetching and instantiating wasm modules. If at all possible, you should use the newer WebAssembly.instantiateStreaming() method instead, which fetches, compiles, and instantiates a module all in one step, directly from the raw bytecode, so doesn't require conversion to an ArrayBuffer."
> Update instantiation MDN link

- src/game-of-life/code-size.md
Comparisons of WebAssembly in terms of code size tend to only take a
look at the size of the wasm file itself and stop there. In terms of
benchmarking though code size is rarely the only factor to consider!
This commit adds a section to the code size section of the book to list
a few other factors which are important to consider when profiling and
measuring code size of wasm files.
> Add a section of handling still-too-big wasm

- src/game-of-life/hello-world.md
I guess the `greet()` function signature was changed and the parameter removed to allow for the exercise at the end of the page.
> 🙈 Make text consistent with code.

- src/game-of-life/code-size.md
- src/game-of-life/time-profiling.md
Hey, I found some parts I thought could be improved a bit.
I want to mention the nightly compiler since from the setup we could've used the beta compiler and wasn't required to use the nightly compiler.
I think one line of explanation of `benchcmp` was a good idea. I also removed the ticks (``) around `benchcmp` since they "broke" the link, it was only displayed that it was a link if you'd hover. See the [current version](https://rustwasm.github.io/book/game-of-life/time-profiling.html) of the book for an example. I included the outputting to files in the `cargo bench` command to make it clear how those files came to be when we will compare them.
> Time profiling updates

- src/game-of-life/code-size.md
By default all debuginfo should be removed in the `wasm-pack`/`wasm-opt`
toolchains, so be sure to mention that!
> Tweak size profiling info about debug info

- src/game-of-life/setup.md
As rust 1.30 is out of beta, this paragraph is no longer needed.
> Update setup.md to reflect that rust 1.30 is out of beta

- src/game-of-life/implementing.md
- src/game-of-life/interactivity.md
**Summary**
This PR adds a `drawGrid()` and `drawCells()` call just before the
first call to `requestAnimationFrame()` in order to ensure that the initial
state of the universe is drawn prior to executing a `Universe.tick()` call.
If this is not done, the initial state of the universe is never drawn,
which can be confusing for those looking to implement the exercises where a
specific starting set of cells is desired.
> Call drawGrid() and drawCells() prior to the first invocation of tick().

- src/game-of-life/setup.md
Update the `rust-install` link. The current link is broken. The updated link takes the user to the current install page on the rust website.
> Update link for rust-install

- src/what-is-webassembly.md
Fixed the following typo:
>A wasm module has access to a single "linear memory", which is essentially a flat array of a bytes
to
>A wasm module has access to a single "linear memory", which is essentially a flat array of bytes
Fixes #152 
> Fix typo under Linear Memory

- .travis.yml
- _theme/header.hbs
The official location for this documentation is now located at
https://rustwasm.github.io/docs/book/ to help pull all the documentation
together. That location is also currently automatically updated, so
this adds a "this is nightly docs" link to the header of this repo's
gh-pages.
> Add a "this is unpublished header" to docs

- src/game-of-life/deploying-to-production.md
This PR fixes the following typos in deploying-to-production.md:
- `and and`-> `and`
- `webserver` -> `web server`
> docs: fix typo in deploying-to-production.md

- src/game-of-life/hello-world.md
An evolution of #156 + a random drive by commit that I noticed at the same time.
@DebugSteven, care to review this?
> Use local file dependencies instead of npm link

- src/game-of-life/hello-world.md
`npm link` method of adding wasm package described in [hello-world.md](https://github.com/rustwasm/book/blob/master/src/game-of-life/hello-world.md) polluting global `npm` package space and is not necessary for tutorial purposes, so I decided to add alternative method. Package can be added by relative path in `www/package.json`.
Though I made it as a footnote, I think maintainers should consider of making it default method, as it much easier than dealing with `npm link`. If so, I can adjust PR. Let me know what you think.
Thank you :-)
> Add alternative to npm link

- src/game-of-life/hello-world.md
Without this pass, the subsequent npm run start would fail with:
```
ERROR in ./index.js
Module not found: Error: Can't resolve 'wasm-game-of-life' in '<basedir>/wasm-game-of-life/www'
@ ./index.js 1:0-42 3:0-10
@ ./bootstrap.js
```
✋ A similar PR may already be submitted!
Please search 🔎 among the [open pull requests][open-prs] before creating one.
Updating the Game of Life tutorial's code? Also send a PR to
[`rustwasm/wasm_game_of_life`!](https://github.com/rustwasm/wasm_game_of_life)
Now that you've checked, it's time to create your PR. 📝
Thanks for submitting! 🙏
For more information, see the [contributing guide][contributing]. 👫
Fixes #___
[contributing]: …
> hello world: reinstall deps before npm run install

- src/reference/add-wasm-support-to-crate.md
"If you're library functions are generic": this is not a contraction of "you are", just the possessive "your".
> you're typo

- src/what-is-webassembly.md
Rawgit is shutting down in the future.
https://rawgit.com/
> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
Thankfully the demo is already hosted from the repository it lives in:
(from https://github.com/WebAssembly/wabt)
So `https://cdn.rawgit.com/WebAssembly/wabt/aae5a4b7/demo/wat2wasm/` _should_ become `https://webassembly.github.io/wabt/demo/wat2wasm/`
> Changed rawgit site to Github pages URL

- src/reference/debugging.md
if this function is named `init` it will conflict with `init` function in the code generated by `wasm-build --target web`
it would produce code like:
```js
/**
*/
export function init() {
wasm.init();
}
// ...
function init(module) {
if (typeof module === 'undefined') {
module = import.meta.url.replace(/\.js$/, '_bg.wasm');
// ...
```
and parsing will fail with:
```
SyntaxError: unknown: Identifier 'init' has already been declared (136:9)
134 | }
135 |
> 136 | function init(module) {
|          ^
137 |     if (typeof module === 'undefined') {
138 |         module = import.meta.url.replace(/\.js$/, '_bg.wasm');
139 |     }
```
> rename `init()` to `init_panic_hook()`

- src/game-of-life/hello-world.md
Explain the **motivation** for making this change. What existing problem does the pull request solve? 
Non npm users might get confused when they can't find a `dependencies` field in the package.json file.
I just did an `npm init wasm-app` following the tutorial, and package.json now only has `devDependencies` out of the box.
Fixes #195
> change 'adding a line to dependencies' to 'adding dependencies'

- src/why-rust-and-webassembly.md
Remove the Greenkeeper project mention as it is shutting down.
Fixes #227
> Drop Greenkeeper mention

- src/reference/crates.md
The existing URI redirects to https://github.com/bytecodealliance/cranelift which then has a note saying the code has moved to https://github.com/bytecodealliance/wasmtime/tree/master/cranelift.
This puts this last URI as the link of the repository.
> Update link to cranelift source code

- src/game-of-life/debugging.md
✋ A similar PR may already be submitted!
Please search 🔎 among the [open pull requests][open-prs] before creating one.
Updating the Game of Life tutorial's code? Also send a PR to
[`rustwasm/wasm_game_of_life`!](https://github.com/rustwasm/wasm_game_of_life)
Now that you've checked, it's time to create your PR. 📝
Thanks for submitting! 🙏
For more information, see the [contributing guide][contributing]. 👫
I made the mistake of adding web-sys twice, and also adding it right in the middle of the dependencies list, just like https://github.com/rustwasm/wasm-bindgen/issues/1039. 
I believe this small change makes it clearer where to add web-sys as a dependency with features.
[open-prs]: …
> make clearer where to add web-sys as dependency in Debugging chapter
