src/game-of-life/setup.md

GoL tutorial: Remove broken exercise

---

src/game-of-life/setup.md
src/wasm-pack/rust-code.md

Some features have been juggled around!

Fix enabled nightly features for newest nightly

---

src/SUMMARY.md
src/game-of-life/production.md

I wasn't sure whether or not to add specific examples for uploading to the server since it seems like a topic that would vary a lot, but I can add a couple if people would find it helpful.
How do you find this @Zetagon?
Closes #50

Add Game of Life Production & Deployment section

---

README.md

Add link to hosted book at beginning of readme

---

src/SUMMARY.md
src/project-templates.md

This should help with discoverability for our project templates.

Add a reference page for available project templates

---

src/game-of-life/hello-world.md
src/game-of-life/setup.md
src/tutorials.md

@fyl2xp1 does this second commit look good to you?

Tutorial setup improvements

---

src/game-of-life/hello-world.md

**Summary**
I hadn't heard of `cargo-generate` before this tutorial so this tripped me up as I went through it. I added a section at the start of the tutorial to indicate that rustup, wasm-pack, and cargo-generate all need to be installed before starting.

List prerequisites for game-of-life tutorial.

---

src/game-of-life/hello-world.md
src/game-of-life/implementing.md
src/game-of-life/rules.md

A couple more tutorial exercise answers and clarifications based on watching a stream of someone going through our tutorial and some recent questions about the "represent a cell as a bit" exercise.

Tutorial exercises

---

src/introduction.md

**Summary**
Update the Rust docs to latest

Update Rust book

---

src/game-of-life/hello-world.md

Explain the **motivation** for making this change. What existing problem does the pull request solve? 
Default `lib.rs` code changed. Updated doc to match this update.

Updated Code Block

---

src/game-of-life/hello-world.md

**Summary**
I was reading through the book and noticed the duplicated word in Section 5.2 in the explanation of [`www/index/html`](https://rustwasm.github.io/book/game-of-life/hello-world.html#wasm-game-of-lifewwwindexhtml).

doc: remove repeated word

---

src/game-of-life/time-profiling.md

✋ A similar PR may already be submitted!
Please search 🔎 among the [open pull requests][open-prs] before creating one.
✋ If there isn't a similar PR, is there an [open issue][open-issues] associated 
with what this PR is trying to solve?
If not, let's create one before opening a PR. ✨
Now that you've checked, it's time to create your PR. 📝
Thanks for submitting! 🙏
For more information, see the [contributing guide][contributing]. 👫
**Summary**

build with debug symbols link 404, should close #125

---

src/game-of-life/hello-world.md

Explain the purpose of `mod utils` in plain English, and provide links to other parts of the tutorial relevant to the purpose of `mod utils`.
Closes #127.
/cc @fitzgen

provide more details about mod utils

---

src/SUMMARY.md
src/reference/add-wasm-support-to-crate.md
src/reference/which-crates-work-with-wasm.md

@alexcrichton does this look complete? Any missing tips you'd recommend adding?

Wasm support in crates

---

src/game-of-life/hello-world.md

> Explain the **motivation** for making this change. What existing problem does the pull request solve? 🤔
a typo in the docs! 😉

game-of-life/hello-world: Fix typo

---

src/game-of-life/implementing.md

Improve second task of Implementing Game of Life section description

---

src/game-of-life/implementing.md

Fixes #135
Even though the pull request fixes the code in the Game of Life project section, I cannot create a pull request into https://github.com/rustwasm/wasm_game_of_life since unable to find the answer code there.

Fix the code of the third exercise answer of Implementing Game of Life section

---

src/game-of-life/implementing.md

✋ A similar PR may already be submitted!
Please search 🔎 among the [open pull requests][open-prs] before creating one.
Updating the Game of Life tutorial's code? Also send a PR to
[`rustwasm/wasm_game_of_life`!](https://github.com/rustwasm/wasm_game_of_life)
Now that you've checked, it's time to create your PR. 📝
Thanks for submitting! 🙏
For more information, see the [contributing guide][contributing]. 👫
In other JavaScript parts, `const` is preferred to `let`. So the part I fixed also should prefer `const`.

Prefer const to let persistently

---

src/game-of-life/hello-world.md

More content that can be copy pasted.
Make it easier for the reader to go through the tutorial. 
I think it would be worth adding some cd command to copy paste further down the same page.

More copy/pasteable content

---

src/game-of-life/rules.md

Fix a typo in rules.md

---

src/game-of-life/testing.md

I think it should be `wasm-pack`

testing: fix typo

---

CONTRIBUTING.md
README.md

There were few grammatical mistakes in readme and contributing.md .
Also , in some places I was able to replace a whole sentence with just one word.
I hope I have done a decent job.

updated README.md and CONTRIBUTING.md

---

src/what-is-webassembly.md

Sorry, this is a super nit-picky wording change, but wanted to get the hang of contributing to this project. Thanks!

Fix for wording issue #192

---

src/game-of-life/hello-world.md

The source code in wasm-pack-template was changed in this [commit](https://github.com/rustwasm/wasm-pack-template/commit/a3acfd295f0a10f2ddb6eebf6db10e057369df6a). 
This commit updates `src/lib.rs` to the newest one to avoid making readers confused.

Update the template source code

---

src/game-of-life/hello-world.md

typo devDependiecs to devDependencies

---

src/what-is-webassembly.md

Update factorial example from using get_local to local.get
